### PR TITLE
fix(truncate): avoid mutation of encoded `obj`

### LINKED ISSUE #46: Truncate Mutates Context Data
When using Elastic APM, any data being logged is mutated during the filter execution of `truncate`. This occurred when I tried to use APM with AWS Lambda. The `result` of the lambda function is attached to the context in https://github.com/elastic/apm-agent-nodejs/blob/abb4f1af4a39e59415bf8977608d928e29e11c72/lib/lambda.js#L45, and this client mutates the output object as a result trimming all headers and the body to 1024 bytes. This results in an invalid AWS lambda response.

### PR DESCRIPTION
**Pull request by Qard**
@blakeembrey I made an update of your PR to use the latest version of breadth-filter and deal with expected truncation behavior.

Fixes #46
Fixes #49

### CODE REVIEW

File: lib/truncate.js [hunk 1]
```diff
@@ -10,192 +10,222 @@ exports.error = truncError
...
-      case 'trace_id':
-      case 'parent_id':
-        max = opts.truncateKeywordsAt
-        break
+      let max = opts.truncateStringsAt
+      switch (path[0]) {
+        case 'name':
+        case 'type':
+        case 'result':
+          value = String(value)
```
Comment (watson) [inline lib/truncate.js]: No need to stringify the value. It will happen inside `truncate()` as well. So these 3 cases can just be combined with the following 3 cases

File: lib/truncate.js [hunk 2]
```diff
@@ -10,192 +10,222 @@ exports.error = truncError
...
 
-  breadthFilter(span, (value, key, path) => {
-    if (typeof value !== 'string') {
-      return value
-    }
+      let max = opts.truncateStringsAt
+      switch (path[0]) {
+        case 'name':
+        case 'type':
+          value = String(value)
```
Comment (watson) [inline lib/truncate.js]: No need to stringify the value. It will happen inside `truncate()` as well. So these 3 cases can just be combined with the following group of cases.

File: lib/truncate.js [hunk 3]
```diff
@@ -10,192 +10,222 @@ exports.error = truncError
...
+      }
+
+      return truncate(value, max)
     }
+  })
 
-    return truncate(value, max)
-  }, true)
+  return Object.assign({
+    name: 'undefined',
```
Comment (watson) [inline lib/truncate.js]: What's the thought behind these `"undefined"` string values?

Comment (Qard) [reply lib/truncate.js]: This is reproducing the behaviour from before where `trans.name = truncate(String(trans.name), opts.truncateKeywordsAt)` would produce `"undefined"` if the name property was undefined because of the explicit string conversion. The `breadthFilter` will skip the field entirely, if not present as it can't operate on a field it's not aware of.

File: lib/truncate.js (hunk 1 above)
Comment (Qard) [reply lib/truncate.js]: fixed

File: lib/truncate.js (hunk 2 above)
Comment (Qard) [reply lib/truncate.js]: fixed

**Comment by Qard** [comment]
Made it handle circular arrays and more closely replicate the original behaviours between the different types. I'll see about restoring the split out header string conversion stuff next...

**Comment by Qard** [comment]
Looking closer, it seems splitting the header string conversion stuff back out will be more complicated than I though, because that would just reintroduce the mutation issue. If I put it _before_ the filter, it mutates in-place, if I put it _after_ the filter, a bunch of stuff could miss truncation.

File: lib/truncate.js (hunk 3 above)
Comment (watson) [reply lib/truncate.js]: Hm true. I'm wondering about the overhead though. Hopefully these properties will always be present. But lets go with it for now

File: lib/truncate.js [hunk 4]
```diff
@@ -243,3 +267,20 @@ function contextLength (path, opts) {
 
   return opts.truncateStringsAt
 }
+
+function isHeader (path) {
+  return path[0] === 'context' && (path[1] === 'request' || path[1] === 'response') && path[2] === 'headers' && path[3]
+}
+
+function onObjectWithHeaders (value, key, path, isNew) {
+  if (isHeader(path)) return value.toString()
```
Comment (watson) [inline lib/truncate.js]: Why not use `String(value)` like you do in `truncTransaction` and `truncError`?

Comment (Qard) [reply lib/truncate.js]: Ah, yeah...good point. Just a second. 😅

Comment (Qard) [reply lib/truncate.js]: fixed.
